### PR TITLE
#122 fixed the composer and mailto triggering at the same time when dealing with event emails

### PR DESCRIPTION
**Pull request by rezk2ll**
composerEvents

* [x] tested with production mode.

### CODE REVIEW

**Review by asmaNode — APPROVED** [review]

**Comment by MichaelBailly** [comment]
This choice brings a really fragile codebase. The day some developer rename the `src/lib/directive.js` file the bug will come back.

I prefer a solution where 

- the mailto handler provides the "new window" behaviour. It's included in the main app.js of each SPA, excluding esn-frontend-inbox
- esn frontend-inbox includes the its main app.js a specific mailto-handler that use the internal composer window

**Review by chamerling — DISMISSED** [review]
Great, it will resolve also https://github.com/OpenPaaS-Suite/esn-frontend-mailto/issues/49 which is partly because of this.

**Comment by chamerling** [comment]
@MichaelBailly is right, the error comes from here

Capture d’écran 2020-09-10 à 17 32 52

The calendar libs must not include the handler

**Comment by chamerling** [comment]
@rezk2ll remove it from lib and add it to the calendar SPA

**Comment by rezk2ll** [comment]
closing this pr since the issue should be fixed in the calendar SPA.

`esn.mailto-handler` was passed down from the `esn-frontend-calendar` ( `esn.calendar.libs` ) to `esn-inbox-calendar` to `esn-frontend-inbox`.

**Pull request closed without merging**
