### PR TITLE
#261 Prevent reopening composer when save as draft fails

### PR DESCRIPTION
**Pull request by oubchid**
https://user-images.githubusercontent.com/7097550/103913442-d4fef900-5108-11eb-817d-b7e795082830.mp4

### CODE REVIEW

**Review by alagane — APPROVED** [review]

**Comment by fabienmoyon** [comment]
No, we need to keep the onFailure action to reopend the composer.
We need to find an other way to fix taht when we are other quota

**Review by chibenwa — CHANGES_REQUESTED** [review]
Loosing user input is not acceptable.

According to me this is a regression.

We can have several options here. One is to invite him, in the failure message, to reopen the composer if he wishes to. (While it might not address the storage space issue it allows copying and pasting the text message to send it via another medium, say Twake.)

**Comment by chibenwa** [comment]
I did read @fabienmoyon message after ;-)

**Comment by tanandy** [comment]
please close PR if this is not applicable

**Comment by chibenwa** [comment]
Will do

**Pull request closed without merging**
