### PR TITLE
#280 Set default home page inbox module to All Mail

### PR DESCRIPTION
**Pull request by oubchid**
1. Redirect to "Inbox" page after login.
Inbox - folder-creation
MP4: https://user-images.githubusercontent.com/7097550/103872872-415d0680-50cf-11eb-992e-54c1090ccb27.mp4

2. Remove Unified Inbox in folder creation modal.
Inbox - OpenPaas (4)

### CODE REVIEW

**Comment by chibenwa** [comment]
`All mails` had not been identified as critical to optimize performance wise.

It requires ElasticSearch, an extra middleware to be rendered server side. This harms plateform resiliency. Extra backend work is required to have similar experience than single mailbox display.

Also, as a user, I care about newly arrived emails, akka INBOX. While having this `All mail` view is usefull (ie I moved an email but do not remember in which mailbox I did put it) I really wonder if - and why - this should be the default behaviour.

From my side, **this is a clear no**.

Cc @MichaelBailly  is this really what we want?

Cc @tanandy to let devops know about some potential infra issues this might cause.

Cc @fabienmoyon  to discuss BA needs behing this work.

**Review by chibenwa — CHANGES_REQUESTED** [review]
See explanation above

**Review by alagane — DISMISSED** [review]

**Comment by fabienmoyon** [comment]
Thanks for the feedback @chibenwa and I'm agree too!

1. Form my side also it should be `Inbox` **by default**.

> Rename Unified Inbox to "None" in folder creation modal.

2. Why, no for me just `Inbox`

**Comment by oubchid** [comment]
> Thanks for the feedback @chibenwa and I'm agree too!
> 
> 1. Form my side also it should be `Inbox` **by default**.
> 
> > Rename Unified Inbox to "None" in folder creation modal.
> 
> 1. Why, no for me just `Inbox`

Modification done here are defined in ticket, so that why "None" and "All Mail" as default home page  
https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/280

**Review by chamerling — APPROVED** [review]

**Review by alagane — APPROVED** [review]

**Review by rezk2ll — APPROVED** [review]

**Pull request merged**
